name: CDK Deploy DEV

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Show workspace structure
      run: |
        echo "Current path:"
        pwd
        echo "Files:"
        ls -R .

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install CDK CLI
      run: npm install -g aws-cdk

    - name: Install CDK Python dependencies
      working-directory: .
      run: pip install -r requirements.txt

    - name: Build Lambda Layer
      working-directory: .
      run: |
        mkdir -p src/layers/deps/python
        pip install -r src/layers/deps/requirements.txt -t src/layers/deps/python

    - name: Add project to PYTHONPATH
      working-directory: .
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: CDK Synth
      working-directory: .
      run: cdk synth

    - name: CDK List
      working-directory: .
      run: cdk ls

    - name: CDK Deploy DEV
      working-directory: .
      run: cdk deploy "DevStage-DevMainStack" --require-approval never
