name: CDK Deploy DEV

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install CDK CLI
      run: npm install -g aws-cdk

    - name: Install CDK Python dependencies
      run: pip install -r requirements.txt

    # 1️⃣ Construcción de layer
    - name: Build Lambda Layer
      run: |
        mkdir -p src/layers/deps/python
        pip install -r src/layers/deps/requirements.txt -t src/layers/deps/python

    # 2️⃣ Agregar ruta del proyecto al PYTHONPATH (PASO CLAVE)
    - name: Add project to PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    # 3️⃣ Autenticación AWS
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    # 4️⃣ Synth
    - name: CDK Synth
      run: cdk synth

    # 3.5️⃣ Mostrar los stacks detectados
    - name: CDK List
      run: cdk ls

    # 5️⃣ Deploy FINAL
    - name: CDK Deploy DEV
      run: cdk deploy DevStage-DevMainStack --require-approval never
